### ISSUE TITLE
TKK is not found - 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by holymode** [bllendev/py-googletrans#7]
If you run for example:
result = translator.detect(text)
trans = translator.translate(text, dest='en')
You will get two prints with the same statement. No errors tho. Everything seems to be working. 
Using the latest version, because I just pip installed it.

**Comment by bllendev** [comment]
that didn't seem to be the prob will do more testing on this soon, may need to better the regex used

**Comment by bllendev** [comment]
nice, thanks for that 

> Sorry, I forgot to add, text is actually a variable and contains text to translate. For testing I used "text = "Беззаперечно seem 장차 ~ 가 되는破碎的 ダウン por el isolement de la langue welke maken die Welt Kuten a จำนวนมาก фрагмент e causa Kwestia polityczna"
> 
> It will result in detected ee but still giving TKK error.
> 
> Also even trying to detect "hello how are you" will result in same error.
> 
> ```
> TKK is not found - 'NoneType' object has no attribute 'group'
> TKK is not found - 'NoneType' object has no attribute 'group'
> Detected(lang=en, confidence=1)
> Translated(src=en, dest=de, text=hallo, wie geht's dir, pronunciation=hello how are you , extra_data="{'translat...")
> ```
> 
> This was the output.

nice thanks for this

**Comment by bllendev** [comment]
will continue this issue here, https://github.com/bllendev/py-googletrans/issues/11
